### ISSUE TITLE
EGCC Taxiway issues

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#100]
If possible, could the taxiways and holding points be re-checked for accuracy compared to the latest charts, many thanks!

P.S Y1 and W1 are fine, but feel free to check

![image](https://user-images.githubusercontent.com/100385372/155616294-afaf132b-08d2-404f-8d10-6c8e0c670486.png)

![image](https://user-images.githubusercontent.com/100385372/155616410-f8c976d6-db48-4a24-8f44-6a9155a56dab.png)

**Comment by Crabcontrollerdave** [comment]
@Danj7572 I've started work on this
