### ISSUE TITLE
AIRAC 2203 - EGAA TUG point symbology

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#105]
TUG points to be added per AD 2.EGPH-2

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/Current-AIRAC/EG_Amdt_A_2022_03_en.pdf

**Comment by Crabcontrollerdave** [comment]
Does anyone have an idea what these Tug points look like? I can't seem to find them on the charts or satellite images

**Comment by RadarController** [comment]
I've just had a proper look at this @Crabcontrollerdave and it's a mistake in the AIRAC, it actually relates to EGAA!

![image](https://user-images.githubusercontent.com/97064113/163712899-e0101236-543c-4fa5-b169-129663dab76b.png)

**Comment by Crabcontrollerdave** [comment]
Ahhhhhhhhh that makes sense! The markings on satellite images look exactly like what is shown on the ground chart. should be easy to add

**Comment by Crabcontrollerdave** [comment]
Here's what I've come up with! I had to make the tug release points larger so they can be seen zoomed out and updated all of the labels to match the chart. I also changed the position of C2 stop bar with it's label.
![aldergrove tug points](https://user-images.githubusercontent.com/97228342/165381055-731dcc80-9994-435b-87e1-8b035cebcdfa.png)

**Comment by RadarController** [comment]
Perfect, all merged in now thank you!
