### ISSUE TITLE
AIRAC 2203 - EGPB information revised

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#111]
Information updated due to incorporation of aerodrome latest survey.

AD 2.12 Runway physical characteristics - True bearing, Runway dimensions. Strip dimensions. RESA dimensions. Displaced threshold. 

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/Current-AIRAC/EG_Amdt_A_2022_03_en.pdf

**Comment by Dogster11** [comment]
I'll have this chris

**Comment by Dogster11** [comment]
Hi Chris, Finished

**Comment by RadarController** [comment]
Thanks, put it in as a pull request (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and we'll check and merge!
