### ISSUE TITLE
EGSS - Add new DET SIDs

### ISSUE THREAD

**Issue by louielister** [IVAO-XU/EG-Sector-File#119]
DET2R/2S

**Comment by Crabcontrollerdave** [comment]
I've just checked now Louie and the latest sector file has both DET2R/2S SID's
![det sids](https://user-images.githubusercontent.com/97228342/158222967-f17e201a-1c49-46d3-982f-5747e399be59.PNG)

**Comment by RadarController** [comment]
Yep I see them too. Going to leave this open until the sectorfile is live on the network however.

**Comment by RadarController** [comment]
Closing this now @louielister as they're in the live file.
