### ISSUE TITLE
AIRAC 2204 - EGGP remove intersection Foxtrot

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#125]
AD 2.12 Runway physical characteristics - RWY 09/27 length, CWY dimensions for RWY 09, Strip dimensions updated. 
AD 2.13 Declared distances - Distances updated and 'Foxtrot' intersection removed as this is no longer used.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_04_en.pdf

**Comment by Crabcontrollerdave** [comment]
I've looked into this @chrisglobe  and I don't think its the physical removal of intersection F, its just the removal of it being an intersection you could depart from

**Comment by RadarController** [comment]
Agreed, would you say removing stop bar F from the sectorfile is sufficient or should we add some markings to the ground layout too?

**Comment by Crabcontrollerdave** [comment]
I would say we don’t need to anything at all Chris, airac 2203, 2204 and 2205 still show the stop bar. My best guess is that as it was only for departure planning for Runway 27. Pilots just wont plan to depart from it and ATC wont use it as a hold point for departures?

**Comment by RadarController** [comment]
Cool, will leave as is in that case, marking as wontfix!
