### ISSUE TITLE
EGNX - Missing taxiway labels, holding points and East apron extension update

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#130]
![Screenshot_166](https://user-images.githubusercontent.com/100385372/160281587-93d7227e-9920-4197-bfbc-6fe2f393a33f.png)

Many thanks

**Comment by Crabcontrollerdave** [comment]
@Danj7572 I’ve started work on this. I managed to add taxiway labels and the east apron but thought id re-do the ground layout to bring it up to date. I’ve changed lots of stands and stand lines also.
