### ISSUE TITLE
Changes to airport GEO files

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#139]
The following has just been posted by the Aurora developer. We'll need to look at all airports going forward.

![Screenshot_20220505-135009.jpg](https://user-images.githubusercontent.com/97064113/166926669-fbfe5a1e-a39c-4481-862c-2f9e349c34c1.jpg)

**Comment by RadarController** [comment]
@Crabcontrollerdave this probably affects you the most as you're smashing off ground layouts 👍

**Comment by Crabcontrollerdave** [comment]
Thanks for the info Chris, would you know if this will apply immediately or only from the next aurora update?
