### ISSUE TITLE
M183 airway not correctly showing

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#151]
M183 between NUGBO and CPT is not routing via SILVA. Code in the low-airways file is correct.

![image](https://user-images.githubusercontent.com/97064113/173798643-6238a7e3-a261-4daa-9243-f5bdfc9ce28e.png)

`T;M183;CPT;CPT;
T;M183;SILVA;SILVA;
T;M183;NUGBO;NUGBO;
T;M183;BKY;BKY;
T;M183;ADMIS;ADMIS;
T;M183;TEDSA;TEDSA;
T;M183;SONDO;SONDO;
T;M183;SONOG;SONOG;
T;M183;REDFA;REDFA;`

**Comment by Crabcontrollerdave** [comment]
I think this might be related but routing this aircraft direct kenet causes a problem 
![image](https://user-images.githubusercontent.com/97228342/184493672-5e14e0c8-20f0-4a41-ab38-2480d34769a3.png)
