### ISSUE TITLE
AIRAC 2207 - EGPD

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#153]
AD 2.EGPD AD 2.10 Aerodrome obstacles.
AD 2.12 Runway physical characteristics - Change to THR elevation.
AD 2.13 Declared distances - Change to RWY 16 TODA distance.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_07_en.pdf

**Comment by Crabcontrollerdave** [comment]
Only one we could do is

> AD 2.12 Runway physical characteristics - Change to THR elevation.

I have checked and the changes are so small there would be no need to update it
