### ISSUE TITLE
AIRAC 2207 - EGPR

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#154]
AD 2.EGPR AIP information revised due to incorporation of aerodrome latest survey.
AD 2.9 Surface movement guidance and control system markings - Windsleeve.
AD 2.12 Runway physical characteristics - THR elevations updated.
AD 2.15 Other lighting, secondary power supply - Anemometer.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_07_en.pdf

**Comment by Crabcontrollerdave** [comment]
The only change we could do is 

> AD 2.12 Runway physical characteristics - THR elevations updated

I've checked but the changes are so small they wouldn't need updating
