### ISSUE TITLE
AIRAC 2207 - EGTC

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#156]
AD 2.EGTC-2 AD 2 EGTC 2-1 Chart revised due to incorporation of aerodrome latest survey.
Addition of Apron 3 at the end of TWY E.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_07_en.pdf

**Comment by Crabcontrollerdave** [comment]
No update can be effected as there is no aerodrome layout for EGTC yet.
