### ISSUE TITLE
AIRAC 2207 - EGBJ

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#157]
AD 2.EGBJ-2 AD 2 EGBJ 2-1 Removal of RWY 18/36. Extension of TWY B and G, TWY D added. Holds. PAPI

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_07_en.pdf

**Comment by Crabcontrollerdave** [comment]
Only Removal of Rwy 18/36 can be effected.
Everything else not required at the moment as there is no aerodrome layout in the sector file.
