### ISSUE TITLE
AIRAC 2207 - EGJB

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#158]
AD 2.EGJB-8 AD 2 EGJB 8-7 and AD 2 EGJB 8-11 Correction to RW27 coordinates.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_07_en.pdf

**Comment by Crabcontrollerdave** [comment]
> AD 2.EGJB-8 AD 2 EGJB 8-7 and AD 2 EGJB 8-11 Correction to RW27 coordinates.

I've checked the coordinates in the AIP vs the sector file and they both match.
