### ISSUE TITLE
Sort procedure fixes alphabetically

### ISSUE THREAD

**Issue by cg341** [IVAO-XU/EG-Sector-File#16]
For faster loading times (albeit small ones!) we should order procedure fixes alphabetically and comment each one with its respective airport ICAO.

**Comment by Crabcontrollerdave** [comment]
I can look into this Chris!

**Comment by RadarController** [comment]
Assigned to you @Crabcontrollerdave, please let me know if you have any questions! :)

**Comment by Crabcontrollerdave** [comment]
Thanks Chris, will do!

**Comment by Crabcontrollerdave** [comment]
Ok @cg341 that's all done, I've committed the changes but I can't find "publish branch" here's what I see: 
![image](https://user-images.githubusercontent.com/97228342/148551905-42a13553-0a71-4398-8bba-87088a89d0a9.png)

**Comment by RadarController** [comment]
If you click current branch -> pull requests -> new pull request can you do it that way?

**Comment by Crabcontrollerdave** [comment]
Thank you Chris that worked! It now should now be in pull requests.

**Comment by RadarController** [comment]
Pull merged, thank you @Crabcontrollerdave!
