### ISSUE TITLE
AC South sector line slightly out

### ISSUE THREAD

**Issue by louielister** [IVAO-XU/EG-Sector-File#164]
![image](https://user-images.githubusercontent.com/31082551/178044021-3da1b3cb-bc4a-49dd-a428-056f68ce3bb4.png)

**Comment by Crabcontrollerdave** [comment]
I could be wrong louie, but Im sure when chris made the dark area, its was based on SFC-195 only. Ive checked the lines and they appear correct. How should the lines look? Nice colour scheme btw 👍

**Comment by Crabcontrollerdave** [comment]
@louielister Is it the sector lines or fill area that's out? The sector lines on both aurora and webeye seem to match ok.  When Chris made the fill area i'm sure it was based on the sfc-195 chart in the uk aip. I've cross referenced the chart and it appears correct. 

![Screenshot_12](https://user-images.githubusercontent.com/97228342/178349225-61414d31-9781-40e3-9fff-5c88af6f6ffd.png)

How should it look Louie?
