### ISSUE TITLE
EGCC Class D error

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#187]
I noticed a line going through the EGCC Class D today
![image](https://user-images.githubusercontent.com/100385372/184547579-bdcf9ff6-4607-4f2d-ac64-7636ffab7d4c.png)

**Comment by Crabcontrollerdave** [comment]
Dan this will be an easy fix and sorted in the next update 😃

**Comment by Crabcontrollerdave** [comment]
Fixed with #213
