### ISSUE TITLE
Use poly fill/line to show airway/CAS structure for airspace when an area unit is online

### ISSUE THREAD

**Issue by JackPlumb** [IVAO-XU/EG-Sector-File#2]
Allow a slightly faded area to be displayed when an area unit comes online allowing you to see areas covered.

**Comment by RadarController** [comment]
Completed for the London FIR. For this to work a new colourscheme is needed, which will be available in the XU wiki.

![image](https://user-images.githubusercontent.com/97064113/156555888-d1ee8c6a-3f8e-42cf-a05d-eea874542f15.png)

Looking to see how the Scottish FIR does it so I can work on that next.

**Comment by Crabcontrollerdave** [comment]
@chrisglobe you can get some good pictures of the upper sectors from the Prestwick video here https://www.nats.aero/news/media-library/
 ![sac high 1](https://user-images.githubusercontent.com/97228342/167019352-9abe42ab-60ec-4a52-912d-3ada976bc092.PNG)

**Comment by RadarController** [comment]
Complete for EGTT_x_CTR and EGPX_M_CTR

Other EGPX sectors in progress!
