### ISSUE TITLE
Check coordinate by EGNS

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#210]
Multiple lines, different coordinate points for the same sections of airspace.
![image](https://user-images.githubusercontent.com/97228342/198288945-b4a7346c-a09b-401f-b416-a99288ee0ee0.png)

**Comment by Danj7572** [comment]
I have investigated this issue and found that the problem lies with EGPX, will make a plan to work on this soon
