### ISSUE TITLE
Heathrow Taxiway lines incomplete.

### ISSUE THREAD

**Issue by AClover96** [IVAO-XU/EG-Sector-File#25]

**Comment by cg341** [comment]
Thanks, I've tagged this as incomplete as it's started but not finished by the looks of it!

**Comment by tim-berry** [comment]
The taxiway lines are correct and only show Code F routes as per the real world.

Found on twitter:
![image](https://user-images.githubusercontent.com/18235887/148355731-1a764e45-533e-4913-bcd8-a9a6776c2a7a.png)

**Comment by RadarController** [comment]
Thanks @tim-berry, marked as wont-fix in that case!
