### ISSUE TITLE
RMAs are not split by runway direction

### ISSUE THREAD

**Issue by cg341** [IVAO-XU/EG-Sector-File#28]
Suggested by 519510

Have easterly and westerly RMAs split out.

**Comment by louielister** [comment]
Following.

**Comment by Crabcontrollerdave** [comment]
Hello! 
Could this work by defining the RMA's under the ACC Sectors or High/Low sectors? You could then Shift+click and switch on/off the ones you need to use? Only problem would be the RMA's would have to be the same colour as the the airspace they are defined under.

**Comment by RadarController** [comment]
That's one possibility but it's a bit of a hacky fix, we've already got an issue of having too many different types of "airspace" split between GEO/ACC/HS/LS and not enough categories to put them under (I'd like to have high and low sectors for ATC boundaries and high and low airspace for...well...airspace!)

My plan is to ask for an Aurora feature request where MRV (which is where the RMAs are currently drawn) can be automatically filtered/selected by active runway - very much like how SIDs and STARs work in labels!

I'll keep you all updated.
