### ISSUE TITLE
Add poly fill/line to show when external area units are online

### ISSUE THREAD

**Issue by JackPlumb** [IVAO-XU/EG-Sector-File#3]

**Comment by RadarController** [comment]
Looking at this now we need to have the following FIRs showing up.

- EGGX
- EISN
- ENOR
- EKDK
- EHAA
- EBBU
- LFFF
- LFEE
- LFRR

However there's different ways we can do this.

1. Polyfill colour for delegated airspace, this works well for EISN, EHAA and LFxx but not the others. 
2. Poly lines that appear when the other sectors come online, but we don't need the full sector boundaries, just a visual representation.

Ideally we need the boundary coordinates out of the database to make this happen though.
