### ISSUE TITLE
High airspace includes ACC

### ISSUE THREAD

**Issue by moorer7** [IVAO-XU/EG-Sector-File#302]
High airspace includes all airspace from ACC, 
![image](https://user-images.githubusercontent.com/11270962/236681972-bd3ab36f-e08d-44ca-8544-5964711f1c24.png)
so data is duplicated. ACC is meant to be the CTR positions and HS to be the actual airspace.

**Comment by Crabcontrollerdave** [comment]
Good spot Ryan will remove in next update
