### ISSUE TITLE
Taxiways + Links

### ISSUE THREAD

**Issue by Rbalfour27** [IVAO-XU/EG-Sector-File#33]
![image](https://user-images.githubusercontent.com/97252428/148436372-ccfd567d-9d38-4355-a7f3-9cf79f0ce897.png)
Could someone add taxiways and links a little like how I've shown, it would be very nice for EGLL to be looking very nice

**Comment by RadarController** [comment]
See #25 about taxiway centrelines, but we might still be able to add taxiway labels as they're fairly easy.

Marking this First Timer Fix if anyone wants to pick it up :)

**Comment by Crabcontrollerdave** [comment]
Would this be what you had in mind @Rbalfour27? Its from an old sector file.
![image](https://user-images.githubusercontent.com/97228342/148591267-761b0693-55a3-4f28-861f-2801416c4df2.png)

**Comment by Rbalfour27** [comment]
> 

Kinda but A and B are put down more often instead of just at that 1 spot

**Comment by moorer7** [comment]
Personally, there is no need for A and B to be labelled as it is unnecessary clutter on the screen, for taxiways that all controllers should know controlling Heathrow.

**Comment by RadarController** [comment]
I have no preference either way. If someone wants to add them go for it. I don't think they need to exist all the way down the taxiways though, perhaps just a couple of locations?

**Comment by Crabcontrollerdave** [comment]
I don't mind either, however I agree with Ryan with having less clutter! if your happy, Im happy to take this project on and il show a screenshot of what I come up?

**Comment by Crabcontrollerdave** [comment]
If you guys are happy, I'm happy to take this on and ill post a screenshot of what I come up with?

**Comment by RadarController** [comment]
That's fine, assigned you to it!

**Comment by Crabcontrollerdave** [comment]
![image](https://user-images.githubusercontent.com/97228342/149019056-69ca6e08-24b5-4493-b965-1ef424c46bfc.png)

Here's what I've come up with, I tried to keep the taxiways as minimal as possible.
I haven't changed anything with the holding point labels, they are the same as before.
A and B Taxiways are where they appear on the uk aip aerodrome chart.

**Comment by RadarController** [comment]
@Rbalfour27 would you be happy with this change please?

**Comment by Rbalfour27** [comment]
> @Rbalfour27 would you be happy with this change please?

Yes it’s look great thanks
