### ISSUE TITLE
Add missing CTA/CTRs

### ISSUE THREAD

**Issue by RadarController** [IVAO-XU/EG-Sector-File#36]
Lots of CTAs and CTRs still to be added to Aurora.

**Comment by Crabcontrollerdave** [comment]
Would this include military MATZ's?

**Comment by RadarController** [comment]
All CTAs and CTRs now included, MATZ can go in /egxx/eg-nav/egxx-military-matz-atz.airspace which I've just created :)

**Comment by Crabcontrollerdave** [comment]
#218
