### ISSUE TITLE
EGKK Taxiway Name

### ISSUE THREAD

**Issue by oliver1234123** [IVAO-XU/EG-Sector-File#400]
Where the red circle is it should say Q as that is what it is on Navigraph.
![image_2023-11-04_170348881](https://github.com/IVAO-XU/EG-Sector-File/assets/122726915/38b66e9f-dd27-45fd-b96e-15499b5dabd5)
![image](https://github.com/IVAO-XU/EG-Sector-File/assets/122726915/29a50818-ee79-463a-a712-1c951ee0bee2)

**Comment by Crabcontrollerdave** [comment]
Thanks @oliver1234123 corrected
