### ISSUE TITLE
Gatwick SMR stands

### ISSUE THREAD

**Issue by louielister** [IVAO-XU/EG-Sector-File#43]
To remove stands 109, 110 & 111 from the SMR. This part of the terminal is under construction and isn't available for parking. 
![image](https://user-images.githubusercontent.com/31082551/149385067-8b66cd3e-57d9-4f8e-b913-47013f3ea2c8.png)

**Comment by RadarController** [comment]
Taxiway Q needs re-drawing too so that it continues perpendicular to L.

**Comment by IslandControl** [comment]
Files created, awaiting conversion KML-TXT

**Comment by RadarController** [comment]
Completed in PR #90
