### ISSUE TITLE
EGKK New Taxiway E, Construction of Rapid Exit Taxiway ER

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#434]
LONDON GATWICK AIRPORT (EGKK) - CONSTRUCTION OF NEW RAPID EXIT TAXIWAY ECHO ROMEO FOR RUNWAY 26L AND NEW TAXIWAY ECHO, CLOSURE OF EXISTING RUNWAY 26L EXIT TAXIWAY ECHO - REPLACES SUP 065/2023

Possibly look at adding the construction areas to make things a bit more interesting?
Possibly could also update SMR.

**Comment by IslandControl** [comment]
Done - 24.01.2024
