### ISSUE TITLE
Airac 2402 - EGNX

### ISSUE THREAD

**Issue by IceDrag-ATC** [IVAO-XU/EG-Sector-File#443]
BPK2P departure no longer exists as of from the 2313 AIRRAC.
![image](https://github.com/IVAO-XU/EG-Sector-File/assets/84091933/cda2ab56-d1d6-43cd-8dbf-8d28c2e8c63e)

**Comment by IslandControl** [comment]
Hi Korey, BPK2P does still exist, not sure what your Source is. Pilots will be offered DTY4P and can expect this SID as a late clearance. This was not in the last AIRAC AMDT that I can see on NATS AIP

**Comment by IslandControl** [comment]
Although the NOTAMS do state this, It is not on the AIP for removal till (2402) - Benched till February

**Comment by IslandControl** [comment]
#464
