### ISSUE TITLE
EGTL

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#446]
Suggested by Korey on the Discord. In shit+click ACC Add EGTL ALL Sector lines. At present we only have the split sectors.

**Comment by IslandControl** [comment]
- Presumably if you turn them all on this works the same?
- When someone logs on to EGTL_CTR (All) does the whole sector turn black outlined anyway?
- Personally I think the split is really useful for who to handoff /Pre-Note/Clearance request to etc. ?

**Comment by Crabcontrollerdave** [comment]
Yeah now you have put it like that, I would agree the same, It makes sense to have the sector splits.
The EGTL Sector doesn't turn black as far as I know, so maybe adding that would be a good idea!
