### ISSUE TITLE
Heathrow GMP Planner frequency

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#457]
124.475 MHz

EGLL_P_GND

**Comment by IslandControl** [comment]
EGLL_P_GND Pending Validation sent with Data.Ivao.Aero

**Comment by IslandControl** [comment]
#461 Merged - Awaiting Approval to close

**Comment by IslandControl** [comment]
Frequency approved by HQ ATC! It's a go!
