### ISSUE TITLE
Addition of EGMD Frequencies

### ISSUE THREAD

**Issue by alexjj111** [IVAO-XU/EG-Sector-File#467]
VID 724361 - EGMD Frequencies do not exist on the Sector File.

EGMD_APP: 120.705
EGMD_TWR: 119.380

Source: https://nats-uk.ead-it.com/cms-nats/opencms/en/Publications/AIP/Current-AIRAC/html/eAIP/EG-AD-2.EGMD-en-GB.html

**Comment by alexjj111** [comment]
Please assign to me.

**Comment by IslandControl** [comment]
#468
