### ISSUE TITLE
2403 - EGPI RWY Designators

### ISSUE THREAD

**Issue by IslandControl** [IVAO-XU/EG-Sector-File#469]
Amend EGPI RWY designators from 13 & 31 to 12 & 30

**Comment by IslandControl** [comment]
Also intersecting RWY 07/25 *

**Comment by alexjj111** [comment]
I can change the designators no problem. Where can I find an official list of changes for AIRAC 2403? I assume that the runway magnetic orientation will require a change on the sector file as well?

**Comment by IslandControl** [comment]
Hi Alex,Are you in XU division, I’m happy to discuss it in a voice chat if you like.Whilst the magnetic variation may change, the Aurora SMR will not change as the magnetic variation obviously does not apply to the drawings on a true north based application.What will need changing as you suggest are the runway designators listed as numbers in the egxx/egtt relevant file and the same for the absolute magnetic heading. So just number changes, no new drawing.If you’re interested in doing more for the sector file whether it interests you or you are interested in a future role etc. we can have a chat about that too!Can you give me your VID too please?Warm regardsDanielSent from my iPadOn 8 Feb 2024, at 20:07, Alexander Juhola-Jones ***@***.***> wrote:﻿
I can change the designators no problem. Where can I find an official list of changes for AIRAC 2403? I assume that the runway magnetic orientation will require a change on the sector file as well?

**Comment by alexjj111** [comment]
@IslandControl my VID is 724361. I'd certainly like to discuss the work on discord VC. Would like to get more in depth with the sector file work done here.

**Comment by IslandControl** [comment]
Hi Alex,

That’s good I’ll have a little look when I’m next in days off and I’ll
email you back with some more information.

Daniel

**Comment by IslandControl** [comment]
#475
