### ISSUE TITLE
2404 - EGPL

### ISSUE THREAD

**Issue by IslandControl** [IVAO-XU/EG-Sector-File#482]
New ATIS frequency

**Comment by IslandControl** [comment]
No Aurora Change possible - Added to DATA.IVAO
@Crabcontrollerdave let me know if this is not the case?

**Comment by Crabcontrollerdave** [comment]
Yeah thats correct @IslandControl you can only change ATIS frequencies through data.ivao.

**Comment by IslandControl** [comment]
Thanks David!. Closed
