### ISSUE TITLE
EGTT_N_CTR Idea for webeye shape to include EGPX_M_CTR (Actually disregard this post)

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#487]
When you control EGTT North you are expected to also control MTMA top down. Currently, the webeye shape only shows EGTT North and not MTMA. This has the potential to cause confusion to pilots departing North out of both EGNX and EGBB. It also has potential to confuse pilots departing Southbound out of EGNX. We do have a position and webeye shape for MTMA However, It's barely used and most controllers prefer the larger EGTT North. It is also very rare to see both North and MTMA on at the same time.

Not requesting for this just yet, just want your thoughts and opinions on if this is a valid solution. The diagram is just a rough draft and may need changing if it is to be considered for real.

Black = Original EGTT North shape
Green = Proposed EGTT North shape

![image](https://github.com/IVAO-XU/EG-Sector-File/assets/100385372/9b8f89e7-ab31-4019-8ed9-cedb86bc9b0d)

**Comment by Danj7572** [comment]
Edit - I just realised we go off high level airspace so doing this method would cause more confusion. Please disregard.

**Comment by IslandControl** [comment]
Hi Dan, agree with your last, LON_C if on might cause more confusion than not with who to contact. Hopefully people don't use just webeye to decide who to contact?!
