### ISSUE TITLE
EGPH Gate 16B has incorrect coordinates

### ISSUE THREAD

**Issue by krenaud** [IVAO-XU/EG-Sector-File#495]
Gate 16B at Edinburgh is not visible. When looking in the sector file I see that it has incorrect coordinates.

Sector file: 16B;EGPH;N055.56.58.690;W055.56.58.690;
NATS: 555658.71N 0032138.09W

Suggested new entry in EGPH.gts: 16B;EGPH;N055.56.58.710;W003.21.38.090;  (Looks good in my Aurora)

**Comment by IslandControl** [comment]
#496
