### ISSUE TITLE
Add gate size information to gates file

### ISSUE THREAD

**Issue by JackPlumb** [IVAO-XU/EG-Sector-File#5]

**Comment by tim-berry** [comment]
Bristol stand sizes

[BRS OSI GO 006   Stand Allocation and Operating Procedures.pdf](https://github.com/IVAO-XU/EG-Sector-File/files/7820616/BRS.OSI.GO.006.Stand.Allocation.and.Operating.Procedures.pdf)

**Comment by IslandControl** [comment]
Hi Guys, I think I can do this so I'll give it a go for KK given my recent KK work and see how it goes!
