### ISSUE TITLE
EGPG add request

### ISSUE THREAD

**Issue by emojisrDEV** [IVAO-XU/EG-Sector-File#529]
I've made a sector (KML) for EGPG since it doesn't actually have a sector so i would like to add it to the sector.

Zack B.

**Comment by emojisrDEV** [comment]
![Capture](https://github.com/IVAO-XU/EG-Sector-File/assets/159626460/844b3ba6-1dcd-4550-baef-455819d3908f)

**Comment by emojisrDEV** [comment]
finished

**Comment by IslandControl** [comment]
@emojisrDEV I have seen your finished product interfaced with our colours as seen below. Unfortunately the level of detail, accuracy in drawing and design is not inline with material we are prepared to merge. There seem to be areas where the Polygon is incomplete (not taken into account a whole shape)like the runway so on this occasion it will not be merged.

![image](https://github.com/IVAO-XU/EG-Sector-File/assets/97858915/9b176f04-98c5-4662-ac22-79a88fc4b008)
