### ISSUE TITLE
EGPH Stand 2a 3a permanently closed

### ISSUE THREAD

**Issue by krenaud** [IVAO-XU/EG-Sector-File#540]
Remove stands 2a / 3a from EGPH. 

NOTAM A2755/24: Edinburgh Airport (EGPH)

A2755/24 NOTAMN
Q) EGPX/QMPLC/IV/BO /A /000/999/5557N00322W005
A) EGPH B) [2404191017](tel:2404191017) C) PERM
E) STANDS 2A AND 3A PERMANENTLY CLOSED.
UK AIP AD 2.EGPH-2-2, AD 2.EGPH-2-3 REFERS.
CREATED: 19 Apr 2024 10:23:00 
SOURCE: EUECYIYN

**Comment by Brad1511** [comment]
Issue On Hold until added to the AIP. For now it is just a NOTAM in real life and on IVAO.
