### ISSUE TITLE
EGPK - Runway markings

### ISSUE THREAD

**Issue by IceDrag-ATC** [IVAO-XU/EG-Sector-File#542]
![image](https://github.com/IVAO-XU/EG-Sector-File/assets/84091933/8b0d8c82-5a92-4cfc-a25c-ebca6e9d7f85)
![image](https://github.com/IVAO-XU/EG-Sector-File/assets/84091933/0739ae41-67f3-4436-94e8-c4c56127afc0)

**Comment by Brad1511** [comment]
#509 already done, 2405 may not have updated yet in Aurora

**Comment by Brad1511** [comment]
#544
