### ISSUE TITLE
Update EGSS/GW Airspace Structure

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#55]
SS/GW airspace is changing with the 2202 AIRAC.  
https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by RadarController** [comment]
This will require a full re-write of file `egxx-base-of-cas.geo` so is unlikely to be done in time for this AIRAC cycle, I'll do my best though!

**Comment by RadarController** [comment]
Fixed in PR #94 .
