### ISSUE TITLE
EGUB creation (in development)

### ISSUE THREAD

**Issue by EmojisrUSA** [IVAO-XU/EG-Sector-File#559]
im seeing if EGUB (an airfield) can be added by me Zack to the sector

**Comment by Brad1511** [comment]
Hi Zack, as previously mentioned several times, the quality of your SMR creation does not meet the standards set in the division. With that in mind, we currently have no plans to implement any new airfields to the UK and Ireland sector file unless requested by the XU ATC Operations team.
Moving on, please refrain from opening up any more 'Issues' or 'Pull requests' unless requested to do so by the ATC Operations team.
Thanks
