### ISSUE TITLE
Various CTA Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#56]
Establishment of the Argyll, Forth, Moray and Tay CTAs and the extension to the Borders CTA 12 and 13
Establishment of Clacton CTA 10, 11 and 12. Daventry CTA 21 amended
Establishment of Daventry CTA 25

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by RadarController** [comment]
As with #55, a re-write of `egxx-base-of-cas.geo` is needed.

**Comment by RadarController** [comment]
Fixed in #94
