### ISSUE TITLE
AIRAC 2202 Coordinate Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#57]
Establishment of new points ZAGZO, JUMZI, EDCOX, COCCU, UDDIZ, OXDUF, ILLOC, OFJES, MUCTE, WIQID, OZZOT and MOREZ
Update to VALBO coordinates

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by jakee2603** [comment]
- [x] ZAGZO, JUMZI, EDCOX, COCCU
- [ ] UDDIZ, OXDUF, ILLOC, OFJES, MUCTE, WIQID, OZZOT and MOREZ
- [ ] VALBO UPDATE

**Comment by jakee2603** [comment]
Working on this

**Comment by jakee2603** [comment]
Completed and Merged

**Comment by RadarController** [comment]
Pull request #67 refers. Closing.
