### ISSUE TITLE
FP Buffer Zones

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#58]
Introduction of Flight Plan buffer zones for EG D323 complex

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by RadarController** [comment]
Before we add these does anyone have any thoughts on them? Do we need to display them on the radar? Noting if we add the 323s we also need to do the other MDAs that have them.

**Comment by RadarController** [comment]
Not required and not displayed in real-world radar displays so closing this off.
