### ISSUE TITLE
LXGB Extended Centrelines

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#585]
![image](https://github.com/user-attachments/assets/25672173-55f1-4d31-8cac-03ffb1d74d56)

Here are the extended centrelines for LGXB I created from the charts and Radar screenshots. If anyone would like to use to add to the sector file or use at will. These are originally from a custom MVA file I added.

Raw code below:

//***27 CIV***
N036.09.17.423;W005.17.57.359;N036.08.59.776;W005.17.56.636;
N036.09.21.928;W005.14.19.231;N036.09.04.160;W005.14.18.353;
N036.09.19.586;W005.16.43.872;N036.09.01.122;W005.16.42.685;
N036.09.02.963;W005.15.30.641;N036.09.20.698;W005.15.31.698;
N036.09.30.359;W005.08.04.970;N036.09.11.742;W005.08.04.126;
N036.09.28.944;W005.09.18.915;N036.09.10.834;W005.09.17.683;
N036.09.27.012;W005.10.34.276;N036.09.08.299;W005.10.32.865;
N036.09.25.248;W005.11.47.399;N036.09.06.975;W005.11.46.533;
N036.09.23.582;W005.13.03.909;N036.09.05.310;W005.13.03.048;
N036.09.21.553;W005.08.04.424;N036.09.05.344;W005.20.27.914;

//***27 MIL***
N036.08.57.561;W005.18.00.214;N036.08.39.651;W005.18.03.226;
N036.07.49.897;W005.08.11.485;N036.07.31.499;W005.08.14.370;
N036.07.57.698;W005.09.24.227;N036.07.40.319;W005.09.26.815;
N036.08.06.921;W005.10.37.406;N036.07.48.630;W005.10.40.869;
N036.08.14.874;W005.11.50.923;N036.07.56.779;W005.11.54.754;
N036.08.23.540;W005.13.03.137;N036.08.05.033;W005.13.05.994;
N036.08.31.899;W005.14.18.744;N036.08.14.308;W005.14.21.526;
N036.08.49.558;W005.16.46.708;N036.08.31.065;W005.16.49.519;
N036.08.40.230;W005.15.30.544;N036.08.22.181;W005.15.33.591;
N036.09.05.303;W005.20.28.083;N036.07.40.855;W005.08.12.990;

//***09 CIV***
N035.59.15.005;W005.24.12.903;N035.59.15.251;W005.23.49.941;
N035.59.14.613;W005.24.00.355;N036.07.51.736;W005.24.11.338;
N036.07.51.736;W005.24.11.338;N036.08.12.832;W005.24.07.356;
N036.08.12.832;W005.24.07.356;N036.08.27.831;W005.23.58.430;
N036.08.27.831;W005.23.58.430;N036.08.39.457;W005.23.46.004;
N036.08.39.457;W005.23.46.004;N036.08.48.324;W005.23.29.855;
N036.08.48.324;W005.23.29.855;N036.08.57.157;W005.23.02.715;
N036.08.57.157;W005.23.02.715;N036.08.59.870;W005.22.45.749;
N036.08.59.870;W005.22.45.749;N036.09.03.168;W005.21.29.088;
N036.08.39.474;W005.24.01.678;N036.08.26.972;W005.23.43.895;
N036.06.57.286;W005.24.20.779;N036.06.57.303;W005.23.58.250;
N036.05.38.155;W005.24.19.692;N036.05.38.171;W005.23.57.042;
N036.04.29.269;W005.24.18.207;N036.04.29.587;W005.23.55.831;
N036.00.11.783;W005.24.12.849;N036.00.12.427;W005.23.50.033;
N036.01.14.654;W005.24.14.347;N036.01.15.402;W005.23.51.515;
N036.02.17.796;W005.24.14.963;N036.02.18.402;W005.23.53.505;
N036.03.21.509;W005.24.17.075;N036.03.22.225;W005.23.54.019;

//***09 MIL***
N035.59.01.621;W005.20.08.168;N035.59.05.417;W005.19.46.524;
N036.07.26.215;W005.23.14.058;N036.07.31.514;W005.22.52.530;
N035.59.03.361;W005.19.57.517;N036.08.28.261;W005.23.25.009;
N036.08.28.261;W005.23.25.009;N036.08.35.315;W005.23.24.980;
N036.08.35.315;W005.23.24.980;N036.08.42.506;W005.23.22.492;
N036.08.42.506;W005.23.22.492;N036.08.48.626;W005.23.17.799;
N036.08.48.626;W005.23.17.799;N036.08.54.177;W005.23.10.238;
N036.08.54.177;W005.23.10.238;N036.08.57.213;W005.23.01.945;
N036.08.57.213;W005.23.01.945;N036.08.59.810;W005.22.45.900;
N036.08.59.810;W005.22.45.900;N036.09.03.170;W005.21.29.287;
N036.00.03.407;W005.20.31.176;N036.00.07.704;W005.20.09.661;
N036.01.05.743;W005.20.31.336;N036.01.00.629;W005.20.52.612;
N036.01.59.522;W005.21.14.051;N036.02.04.310;W005.20.52.046;
N036.03.00.014;W005.21.36.552;N036.03.05.148;W005.21.14.554;
N036.03.59.888;W005.21.58.445;N036.04.04.931;W005.21.36.591;
N036.05.02.188;W005.22.20.634;N036.05.07.216;W005.21.59.560;
N036.06.07.676;W005.22.45.416;N036.06.12.981;W005.22.23.242;

**Comment by IslandControl** [comment]
Hi Dan, thanks we will put these to good use in another location
