### ISSUE TITLE
London North - MTMA Shaded Area when active

### ISSUE THREAD

**Issue by Danj7572** [IVAO-XU/EG-Sector-File#603]
![image](https://github.com/user-attachments/assets/ac42a822-baa5-443e-87c1-a26379928b5e)

Hi guys, what's your thoughts on adding an adding the MTMA Shaded area to the London North shaded area to show their top down responsibilities for MTMA to other controllers. I'm not sure if this already exists under MTMA or if it would need to be added. Regardless, I am happy to get this working for you if it's something you would like added.

**Comment by Danj7572** [comment]
![image](https://github.com/user-attachments/assets/36be4897-3d12-4665-905a-5c3f847c9913)

I updated the PLF file for EGPX_M_CTR to include EGTT_N_CTR

**Comment by IslandControl** [comment]
Looks cool, send it through! Brad has been mostly helping sort these out while I've been away. I will attest to not having given much more thought than If it is better than what we currently have... merged. So yes let's improve it for sure

**Comment by IslandControl** [comment]
Merged #604
