### ISSUE TITLE
MRVA EGKK

### ISSUE THREAD

**Issue by manuelnuez** [IVAO-XU/EG-Sector-File#609]
Hi! I believe the CAS base altitude for the Gatwick CTA should be 1500 instead of 2500 as shown here:

![Screenshot 2024-08-31 151707](https://github.com/user-attachments/assets/c06f943c-8c8a-4686-a997-ecf16b8070bd)
![Screenshot 2024-08-31 151735](https://github.com/user-attachments/assets/cd34d73c-fbb9-4d6b-9f02-92acab7635ae)

**Comment by IslandControl** [comment]
Hi Manuel, quite right. I will get this amended, Thank you
