### ISSUE TITLE
AIRAC 2202 EGCN Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#61]
AD 2.EGCN-5 AD 2 EGCN 5-1 Update to Doncaster RADAR frequencies

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by RadarController** [comment]
Changes made in IVAO database for this. AIRAC change is to a UHF frequency (not currently supported).

Taken the opportunity to add EGCN to the ATC list in Aurora though!
