### ISSUE TITLE
AIRAC 2202 - EGGW Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#62]
AD 2.EGGW AD 2.2 Aerodrome geographical and administrative data - AD elevation updated.
AD 2.EGGW AD 2.18 Air traffic services communication facilities - Removal of ESSEX RADAR callsign and 128.750 MHz frequency

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by jakee2603** [comment]
#75
