### ISSUE TITLE
AIRAC 2202 - EGSS Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#63]
AD 2.EGSS-4 AD 2 EGSS 4-1 LTMA 2 removed. LTMA 3 and Stansted CTA 3 updated.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by RadarController** [comment]
Fixed in #94
