### ISSUE TITLE
AIRAC 2202 - EGPB Changes

### ISSUE THREAD

**Issue by Bucklerz** [IVAO-XU/EG-Sector-File#65]
AD 2.EGPB-3 AD 2 EGPB 3-1 and 3-1 Moray TMZ and Class E CTA 3,4,5 and 16 added.

https://nats-uk.ead-it.com/cms-nats/export/sites/default/en/Publications/AIP/EG_Amdt_A_2022_02_en.pdf

**Comment by jakee2603** [comment]
#76

**Comment by RadarController** [comment]
All fixed now in #76 and #94
