### ISSUE TITLE
Gatwick missing taxiways

### ISSUE THREAD

**Issue by Crabcontrollerdave** [IVAO-XU/EG-Sector-File#662]
![image](https://github.com/user-attachments/assets/2abc213f-98b9-4472-8e4a-5bd2a04eb72a)

I just noticed a few of the taxiway labels are misssing at Gatwick, just in case no ones spotted it.

**Comment by IslandControl** [comment]
Hi Dave, we will look to see if we can separate the Stopbars from the taxiways and get this added for you, so that users can choose between having them visible
