### ISSUE TITLE
London/Scottish FIR Foreign Sectors Light Up

### ISSUE THREAD

**Issue by IslandControl** [IVAO-XU/EG-Sector-File#665]
Light up foreign sectors when online for coordination same as our Areas in defined colour

EGPX (?already complete)
EISN (including _C_)
EIDW_N (including _S_)
LFRR
LFEE
LFFF
EBBU
EHAA (Including Maastricht)
EKDK
ENOR

## Shapes on request, do not need to be redrawn manually!

**Comment by IslandControl** [comment]
@Brad1511 Ryan M has stated he is happy to help with this and also has some ideas about Transfer list options now available in Public versions. Although I would like a separate issue for that when it arises. Would be great to get these done first

**Comment by moorer7** [comment]
#667

**Comment by IslandControl** [comment]
Added, awaiting:

ENOR
BIRD
EBBU
EISN/EIDW
EKDK

**Comment by IslandControl** [comment]
#670

**Comment by IslandControl** [comment]
#676 
Added
ENOR
BIRD
EBBU
EISN
EIDW
EGGX/CZQX

**Comment by IslandControl** [comment]
EKDK added now all complete
