### ISSUE TITLE
Luton Gate

### ISSUE THREAD

**Issue by louielister** [IVAO-XU/EG-Sector-File#82]
To add the Luton Gate (a line) into the sectorfile.

**Comment by moorer7** [comment]
I see no need as in next AIRAC it will not exist.

**Comment by louielister** [comment]
> I see no need as in next AIRAC it will not exist.

Are we sure it's going to go? I'd imagine it will still be used for flights travelling from Stansted to Luton and for the LOGAN2A and DET2A STARs.

**Comment by RadarController** [comment]
I think this would be better served in the documentation?

**Comment by louielister** [comment]
> I think this would be better served in the documentation?

Yes it'd be included in documentation but a visual line/border of where it is on the airspace sector file would be beneficial. It is only a line.

**Comment by RadarController** [comment]
Possible fix/workaround 

![image](https://user-images.githubusercontent.com/97064113/154161960-281523aa-0baf-4fdf-a87f-d7c12e20c195.png)
