### ISSUE TITLE
LELNA1J arrival for EGJJ

### ISSUE THREAD

**Issue by HeathrowRadar** [IVAO-XU/EG-Sector-File#83]
When you enter the LELNA STAR for EGJJ:
![screenshot](https://user-images.githubusercontent.com/99101750/152661732-2b460be4-b5a8-4007-8f61-70c1986cfcd0.png)

Goes back to normal after normal after you clear the WP box

**Comment by RadarController** [comment]
This is a problem with all EGJJ SID/STARs by the looks of it.

@moorer7 as we've just discussed!

**Comment by RadarController** [comment]
This was actually caused by an EGHH SID, and will be resolved in the next update. Just putting a PR in.
