### ISSUE TITLE
LAMIX2X for Leeds

### ISSUE THREAD

**Issue by HeathrowRadar** [IVAO-XU/EG-Sector-File#96]
LAMIX SID for Leeds (EGNM) shows a waypoint up to the north of Scotland. Not too sure if anything else is wrong.

Cheers!
![image](https://user-images.githubusercontent.com/99101750/154757719-e5b95be3-d1d4-4c57-aabc-d7837d2c7396.png)

**Comment by RadarController** [comment]
Already fixed in #95 :)
